-- Seed the original arenadosbonus.com static offers into the standalone
-- external offers table managed from /admin/external-sites.

with arena_site as (
  insert into external_offer_sites (
    slug,
    name,
    title,
    description,
    cta_label,
    is_active
  ) values (
    'arena-dos-bonus',
    'Arena dos Bónus',
    'Ofertas da Arena dos Bónus',
    'Ofertas escolhidas e atualizadas através do painel Brutuspolus.',
    'Apostar Agora',
    true
  )
  on conflict (slug) do update set
    name = excluded.name,
    title = excluded.title,
    description = excluded.description,
    cta_label = excluded.cta_label,
    is_active = true,
    updated_at = now()
  returning id
),
resolved_site as (
  select id from arena_site
  union all
  select id from external_offer_sites where slug = 'arena-dos-bonus'
  limit 1
),
source_offers (
  slug,
  name,
  logo_url,
  banner_url,
  badge,
  tags,
  headline,
  bonus_value,
  free_spins,
  min_deposit,
  code,
  cashback,
  withdraw_time,
  license,
  established,
  notes,
  affiliate_url,
  cta_label,
  rating,
  visible,
  featured,
  sort_order
) as (
  values
    (
      'smoking-ace',
      'SMOKING ACE',
      'https://i.imgur.com/IzGDLVV.png',
      null,
      null,
      array['10 FS Sem Depósito', 'Rollover 50x', 'Cripto', 'Clube VIP']::text[],
      '125% no 1º Depósito + 125 Freespins',
      '225% até €2k',
      '225 FS',
      '€25',
      'Brutus',
      null,
      '0-24h',
      '',
      '2023',
      array[
        '1º Depósito: 125% + 125 Freespins',
        '10 Freespins sem depósito no registo',
        'Rollover: 50x | Ganho máx: 25€',
        'Levantamento mínimo: €20 | Sem taxas',
        'Limites: €1.000/transação, €3.000/dia, €50.000/mês'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIiQAbEseutvtGNd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      0
    ),
    (
      'winhugo',
      'WINHUGO',
      'https://dibv43v5qvczy.cloudfront.net/tenant2c6d3f79-41c3-4a38-99bb-0efbe511b6c2/MyqJnaYEE8nUnSdYSpvOY9DM4ZzCvQPbmw8LGTdl.png',
      null,
      null,
      array['Non-Sticky Bónus', 'Rollover 25x', 'MB Way', 'Cripto']::text[],
      '100% até 1000€ + 100 Freespins',
      '100% até €1k',
      '100 FS',
      '€10',
      'brutus',
      null,
      'N/A',
      '',
      '',
      array[
        'Bónus Non-Sticky',
        '1º Depósito: 100% até €1.000 + 100 Freespins',
        'Depósito mínimo: €10',
        'Rollover: 25x',
        'Ganho máximo com bónus: 100% do valor depositado'
      ]::text[],
      'https://www.winhugo1.com/a/brutus',
      'Registar Agora',
      5.0,
      true,
      false,
      1
    ),
    (
      'lollyspins',
      'LOLLYSPINS 🍭',
      'https://i.imgur.com/He5Iwgb.png',
      null,
      null,
      array['Cashback 35%', '350 FS', 'Hacksaw', 'Push Gaming']::text[],
      '400% Bónus até €2200 & 350 Rodadas Grátis',
      '400% até €2.2k',
      '350 FS',
      '25€',
      '',
      '35%',
      '0-24h',
      '',
      '',
      array[
        '1º depósito: 100% de bónus + 100 Freespins Wanted Dead or a Wild',
        '2º depósito: 80% de bónus + 50 Freespins Razor Returns',
        '3º depósito: 70% de bónus + 100 Freespins Duel at Dawn',
        '4º depósito: 50% de bónus',
        '5º depósito: 100% de bónus + 100 Freespins Pirate Bonanza'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIiBYt4A521OEWNd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      2
    ),
    (
      'rioace',
      'RIOACE',
      'https://i.imgur.com/YOiAa7X.png',
      null,
      null,
      array['350 FS', 'Cripto', 'Apps móveis', 'Casino ao vivo']::text[],
      '400% Bónus + 350 Freespins',
      '400% até €2.2k',
      '350 FS',
      '20€',
      '',
      null,
      '0-24h',
      '',
      '2024',
      array[
        '400% Bónus + 350 Freespins no 1º depósito',
        'Sem taxas de depósito',
        'Sem taxas de levantamento',
        'Limites: €10.000/dia, €50.000/mês',
        'Casino ao vivo, Apps móveis e Desportos'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIhZNvOoThXn9GNd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      3
    ),
    (
      'stelario',
      'STELARIO',
      'https://i.imgur.com/BCoqD0u.png',
      null,
      null,
      array['100 FS', 'Rollover 40x', 'Cripto', 'Clube VIP']::text[],
      '100% até 300€ + 100 Freespins',
      '100% até €300',
      '100 FS',
      '€25',
      '',
      null,
      '0-48h',
      '',
      '2020',
      array[
        '100% até 300€ + 100 Freespins Gates of Olympus',
        'Depósito mínimo: €25 | Aposta máxima: €5',
        'Freespins creditadas a cada 24h',
        'Rollover: 40x',
        'Levantamento mínimo: €20'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIjsP_BZ5nQwFmNd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      4
    ),
    (
      'windetta-casino',
      'Windetta Casino',
      'https://i.imgur.com/TWSvgYw.png',
      null,
      null,
      array['Escolhe o teu Bónus', 'Até 400 FS', 'Cripto', 'Clube VIP']::text[],
      'Casino',
      '230% até €2000',
      'Até 400 FS',
      '€25',
      '',
      null,
      '0-24h',
      '',
      '',
      array[
        '5 Bónus de Boas-Vindas Disponíveis',
        '1º - 230% até 2000€',
        '2º - 400 Freespins',
        '3º - 200% até 2000€ + 200 Freespins',
        '4º - 150% até 2000€ + 300 Freespins'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIgxE7I3F4wd8mNd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      5
    ),
    (
      'dbbet',
      'DBbet ⚽',
      'https://i.imgur.com/V3rhnV9.png',
      null,
      null,
      array['30 FS', 'MB Way', 'Casino', 'Apostas']::text[],
      '400% Bónus até €2200 & 350 Rodadas Grátis',
      '100% até €300',
      '30 FS',
      '10€',
      'BRUTUS',
      null,
      '0-24h',
      '',
      '',
      array[
        'Cria uma conta e preenche os dados pessoais',
        'Ativa o número de telefone',
        'Bónus creditado automaticamente após depósito elegível',
        'Ativa a receção de bónus nas configurações da conta',
        '24/7 Suporte ao vivo'
      ]::text[],
      'https://dbbt.me/BRUTUS',
      'Registar Agora',
      5.0,
      true,
      false,
      6
    ),
    (
      'spinko',
      'Spinko 🏋️',
      'https://i.imgur.com/aWBVQb8.png',
      null,
      null,
      array['Cashback até 35%', 'Até 350 FS', 'Wager 40x', 'Cripto']::text[],
      '400% Bónus até €2200 & 350 Rodadas Grátis',
      '400% até €2200',
      'Até 350 FS',
      '25€',
      '',
      'até 35%',
      '0-48h',
      '',
      '',
      array[
        '1º depósito: 100% de bónus + 100 rodadas grátis',
        '2º depósito: 80% de bónus + 50 rodadas grátis',
        '3º depósito: 70% de bónus + 100 rodadas grátis',
        '4º depósito: 50% de bónus',
        '5º depósito: 100% de bónus + 100 rodadas grátis'
      ]::text[],
      'https://record.joinaff.com/_hwHCWKmquIjCeYbrF0gqI2Nd7ZgqdRLk/1/',
      'Registar Agora',
      5.0,
      true,
      false,
      7
    ),
    (
      'gameslots',
      'GAMESLOTS 🏋️',
      'https://i.imgur.com/FBMB4lB.png',
      null,
      null,
      array['ATÉ 3000€ EM BÓNUS', 'MB Way', 'Cripto']::text[],
      'ATÉ 3000€ EM BÓNUS',
      'ATÉ 3000€',
      '',
      '10€',
      'BRUTUS',
      null,
      '0-48h',
      '',
      '',
      array['ATÉ 3000€ EM BÓNUS']::text[],
      'https://m.gslotspartners.com/redirect.aspx?mid=1&sid=108&cid=&pid=&affid=62',
      'Registar Agora',
      5.0,
      true,
      false,
      8
    ),
    (
      'spinline',
      'SpinLine',
      'https://i.imgur.com/kxC9EOk.png',
      null,
      'NEW',
      array['Novo', '200 FS', 'Rollover 40x', 'Cripto']::text[],
      '100% até 300€ + 200 Freespins',
      '100% até €300',
      '200 FS',
      '€20',
      '',
      null,
      'N/A',
      '',
      '',
      array[
        'Depósito de 20€: 100% até 50€ + 30 RG',
        'Depósito de 50€: 100% até 200€ + 80 RG',
        'Depósito de 200€: 100% até 300€ + 200 RG',
        'Depósito mínimo: €20',
        'Rollover: 40x'
      ]::text[],
      'https://partners.meratrack.xyz/click?o=996&a=1091',
      'Registar Agora',
      5.0,
      true,
      false,
      9
    )
)
insert into external_site_offers (
  site_id,
  slug,
  name,
  logo_url,
  banner_url,
  badge,
  tags,
  headline,
  bonus_value,
  free_spins,
  min_deposit,
  code,
  cashback,
  withdraw_time,
  license,
  established,
  notes,
  affiliate_url,
  cta_label,
  rating,
  visible,
  featured,
  sort_order
)
select
  resolved_site.id,
  source_offers.slug,
  source_offers.name,
  source_offers.logo_url,
  source_offers.banner_url,
  source_offers.badge,
  source_offers.tags,
  source_offers.headline,
  source_offers.bonus_value,
  source_offers.free_spins,
  source_offers.min_deposit,
  source_offers.code,
  source_offers.cashback,
  source_offers.withdraw_time,
  source_offers.license,
  source_offers.established,
  source_offers.notes,
  source_offers.affiliate_url,
  source_offers.cta_label,
  source_offers.rating,
  source_offers.visible,
  source_offers.featured,
  source_offers.sort_order
from source_offers
cross join resolved_site
on conflict (site_id, slug) do update set
  name = excluded.name,
  logo_url = excluded.logo_url,
  banner_url = excluded.banner_url,
  badge = excluded.badge,
  tags = excluded.tags,
  headline = excluded.headline,
  bonus_value = excluded.bonus_value,
  free_spins = excluded.free_spins,
  min_deposit = excluded.min_deposit,
  code = excluded.code,
  cashback = excluded.cashback,
  withdraw_time = excluded.withdraw_time,
  license = excluded.license,
  established = excluded.established,
  notes = excluded.notes,
  affiliate_url = excluded.affiliate_url,
  cta_label = excluded.cta_label,
  rating = excluded.rating,
  visible = excluded.visible,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  updated_at = now();
